### ISSUE TITLE
Suicides

### ISSUE THREAD

**Issue by hdt80** [hdt80/topt#14]
[DPSO]Slatter1: "<00:03:38> "[PIZZADUDE]driver": "suicide" AND "killed by explosive"
<00:04:07> "[PIZZADUDE]driver": That would be successful suicide bombings
<00:04:21> "[PIZZADUDE]driver": All suicide bombings would just be suicide + explosive death
<00:04:45> "[PIZZADUDE]driver": suicide + explosive death + got a kill within 1 second"

**Comment by activedecay** [comment]
lmao does this work now? people gone jihad
